radicalbit/radicalbit-ai-monitoring

CNAME
As title, this should be the first step, then we must add DNS records where needed
=> chore: add cname file for gh pages custom domain

spark/jobs/utils/current.py, spark/jobs/utils/reference.py
removed all the .count() in reference.py and current.py and replaced with attribute that should be computed just one time and speed up the spark jobs
=> fix(spark): removed all .count() and replaced with attribute in the class 

ui/src/components/modals/current-import-detail-modal/index.jsx
show filename in import-detail-modal header
=> fix(ui): show filename in import-detail-modal header

api/app/db/dao/model_dao.py, api/app/routes/model_route.py, api/app/services/model_service.py, api/tests/dao/model_dao_test.py, api/tests/routes/model_route_test.py, api/tests/services/model_service_test.py, sdk/radicalbit_platform_sdk/client.py, sdk/radicalbit_platform_sdk/models/__init__.py, sdk/radicalbit_platform_sdk/models/model_definition.py, sdk/tests/client_test.py
Added get all models not paginated API + updated SDK implementation to use new API
=> feat: get all models not paginated

sdk/radicalbit_platform_sdk/apis/model.py
added ability to get all reference and current datasets for a specific model
=> feat(sdk): get all reference and current datasets

.github/workflows/radicalbit-bot.yaml, CONTRIBUTING.md
This will add contributing guide on how to setup the development environment, code style, and bot commands to trigger the build.
This will also align build-all command on bot by adding the `/` prefix.
=> docs: enhanced CONTRIBUTING.md file

sdk/radicalbit_platform_sdk/apis/model.py, sdk/radicalbit_platform_sdk/models/aws_credentials.py
updated `AwsCredentials` adding `endpoint_url` property in order to be able to change it in case of other S3 compatible solutions
=> feat(sdk): added ability to set S3 endpoint url if needed

.github/workflows/trivy-scan.yaml
It is now using the new release with last fixes
=> ci: restored workflow version for trivy scan

spark/jobs/utils/chi2.py, spark/jobs/utils/current_binary.py, spark/jobs/utils/ks.py, spark/tests/binary_drift_test.py
updated ks test and chi2 test with new phi value, fixed reference and current columns in class, fixed chi2 has_drift
=> fix: updated ks test and chi2 test

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml
=> chore: Update config.yml

ui/src/container/models/Details/multi-classification/reference/data-quality/data-point-distribution/options.js
=> fix(ui): remove space

spark/jobs/current_job.py, spark/jobs/metrics/data_quality_calculator.py, spark/jobs/metrics/model_quality_regression_calculator.py, spark/jobs/utils/current_regression.py, spark/tests/regression_current_test.py
This will add Regression Data Quality to spark job for current dataset.
Here the result:
=> feat(spark): added data quality for current regression

spark/jobs/metrics/data_quality_calculator.py, spark/jobs/models/data_quality.py, spark/jobs/utils/current_binary.py, spark/jobs/utils/current_multiclass.py, spark/jobs/utils/reference_binary.py, spark/jobs/utils/reference_multiclass.py, spark/tests/binary_current_test.py, spark/tests/binary_reference_test.py, spark/tests/multiclass_current_test.py, spark/tests/multiclass_reference_test.py
Added calculations for occurrencies of prediction labels for both binary and multiclass and for both current and reference
Updated the tests following the previous change
=> feat: added support to binary and multiclass for predictions

docs/quickstarts/README.md, docs/quickstarts/notebooks/binary-classification-income-data.ipynb, docs/quickstarts/poetry.lock
This PR implements a little modification in the BInary Classification Tutorial, which are:
- adding the dataset quote into the notebook
- adding the dataset quote into the README
=> docs: adding quotes in the binary class tutorial

ui/src/components/ErrorPage/no-features.jsx, ui/src/components/modals/add-new-model/step-one/form-fields.jsx, ui/src/container/models/Details/binary-classification/current/data-drift/list/index.jsx, ui/src/container/models/Details/binary-classification/current/data-quality/data-quality-list/index.jsx, ui/src/container/models/Details/binary-classification/reference/data-quality/data-quality-list/index.jsx, ui/src/container/models/Details/multi-classification/current/data-drift/list/index.jsx, ui/src/container/models/Details/multi-classification/current/data-quality/data-quality-list/index.jsx, ui/src/container/models/Details/multi-classification/current/imports/index.jsx, ui/src/container/models/Details/multi-classification/reference/data-quality/data-quality-list/index.jsx, ui/src/container/models/Details/regression/current/data-drift/list/index.jsx, ui/src/container/models/Details/regression/current/data-quality/data-quality-list/index.jsx, ui/src/container/models/Details/regression/reference/data-quality/data-point-distribution/options.js, ui/src/container/models/Details/regression/reference/data-quality/data-quality-list/index.jsx, ui/src/store/state/models/constants.js
- add empty list void when feature not available
- change order in modelType
=> feat(ui): add empty list void when feature not available

ui/src/store/state/models/polling-hook.js
=> fix(ui): fix polling issue

spark/jobs/metrics/model_quality_regression_calculator.py
return value for regression line casted to float
=> fix: return value for regression line casted to float

spark/jobs/metrics/model_quality_regression_calculator.py, spark/tests/results/regression_current_results.py, spark/tests/results/regression_reference_results.py
return values for regression line changed from points to coefficient and intercept
fixed consequent tests
=> fix: return values for regression line changed from points to coeff

ui/src/container/models/Details/regression/current/model-quality/index.jsx, ui/src/container/models/Details/regression/reference/model-quality/index.jsx
=> fix(ui): fix regression resize chart

api/app/models/metrics/drift_dto.py
=> fix: added psi to enum drift dto

spark/jobs/metrics/data_quality_calculator.py, spark/jobs/metrics/model_quality_regression_calculator.py, spark/jobs/metrics/psi.py, spark/jobs/models/current_dataset.py, spark/jobs/models/reference_dataset.py, spark/jobs/utils/current_binary.py, spark/jobs/utils/current_multiclass.py, spark/jobs/utils/misc.py, spark/jobs/utils/reference_binary.py, spark/jobs/utils/reference_multiclass.py
finished refactoring for withcolumn prefix
=> fix: finished refactoring for withcolumn prefix

ui/src/container/models/Details/binary-classification/current/model-quality/charts.jsx, ui/src/container/models/Details/binary-classification/current/model-quality/columns.jsx, ui/src/container/models/Details/binary-classification/current/model-quality/index.jsx, ui/src/container/models/Details/binary-classification/reference/model-quality/columns.jsx, ui/src/container/models/Details/binary-classification/reference/model-quality/index.jsx, ui/src/container/models/Details/constants.js
- add logLoss to modelQuality binary
=> feat(ui): add logLoss to modelQuality binary

ui/src/constants.js
Implementation:
- add PSI label
=> feat(ui): add PSI label

ui/src/container/models/Details/binary-classification/current/data-drift/header/index.jsx, ui/src/container/models/Details/binary-classification/current/data-drift/list/index.jsx, ui/src/container/models/Details/binary-classification/current/data-drift/use-get-filtered-features.js, ui/src/container/models/Details/multi-classification/current/data-drift/header/index.jsx, ui/src/container/models/Details/multi-classification/current/data-drift/list/index.jsx, ui/src/container/models/Details/multi-classification/current/data-drift/use-get-filtered-features.js, ui/src/container/models/Details/regression/current/data-drift/header/index.jsx, ui/src/container/models/Details/regression/current/data-drift/list/index.jsx, ui/src/container/models/Details/regression/current/data-drift/use-get-filtered-features.js, ui/src/store/state/models/api.js, ui/src/store/state/models/mock/current_drift.json
- refactor drift section with field type
=> feat(ui): refactor drift section with field type

README.md
Updated README file with data privacy.
=> docs: updated README file.

docs/docs/l5_python_sdk.md
updated SDK documentation:
* added doc for `update_features` method
* removed empty spaces
=> docs: update SDK documentation

docs/docs/l5_python_sdk.md
aligned SDK documentation indentations in order to improve readability
=> docs: align SDK indentations

.github/workflows/prepare-docs-for-release.yaml
As title, pipeline has an invalid syntax
=> ci: fix pipeline to create documentation version

.github/workflows/prepare-docs-for-release.yaml
As title, the double quotas is preventing the pipeline from working correctly
=> ci: remove wrong double quotas in pipeline

RELEASE.md
The document has been rewritten to a better form
=> docs: update RELEASE.md document

ui/src/constants.js, ui/src/container/app/content-switch/header.jsx, ui/src/container/launchpad/header.jsx, ui/src/container/launchpad/index.jsx, ui/src/container/launchpad/routes.jsx, ui/src/container/layout/index.jsx, ui/src/container/layout/layout-provider/index.js, ui/src/main.jsx
- add new route for `launchpad`
- add launchpad components with basic grid template
=> feat(ui): add new launchPad route and components

ui/src/constants.js, ui/src/container/app/content-switch/header.jsx, ui/src/container/launchpad/index.jsx, ui/src/container/launchpad/routes.jsx, ui/src/container/launchpad/top-row/index.jsx, ui/src/container/layout/index.jsx, ui/src/container/layout/layout-provider/index.js
- add TopRow components
- add external path to ExternalPathEnum
=> feat(ui): add topRow in launchPad page

api/app/db/dao/model_dao.py, api/app/services/model_service.py, api/poetry.lock, api/pyproject.toml, api/tests/dao/model_dao_test.py, api/tests/routes/model_route_test.py, api/tests/services/model_service_test.py
added percentage returns to get_models_paginated
if no current is uploaded, percentages will be null
added tests
=> feat: added percentage to get_models_paginated

api/app/db/dao/model_dao.py, api/app/routes/model_route.py, api/app/services/model_service.py, api/tests/routes/model_route_test.py, api/tests/services/model_service_test.py
new endpoint "/tot_percentages" for summarized percentages across all models
edited tests
=> feat: get_summarized_percentages endpoint

ui/src/components/charts/line-chart/index.jsx, ui/src/container/models/List/index.jsx, ui/src/helpers/common-chart-options.js
- remove console.debug
- remove modelsWithMock
- remove boundaryGap
=> fix(ui): minor fixies

ui/src/container/launchpad/right-column/alerts.jsx
- remove datatable for alerts list visualization
=> fix(ui): remove datatable for alerts list visualization

ui/src/container/launchpad/right-column/alerts.jsx
- remove overflow on alerts list
=> fix(ui): remove overflow on alerts list

README.md
This PR adds the Launchpad screenshot in the README of the main project.
=> docs: add launchpad screen in README

RELEASE.md
Added step to optionally change the semver version
=> docs: update release document

ui/package.json, ui/src/container/models/Details/binary-classification/current/data-quality/data-point-distribution/index.jsx, ui/src/container/models/Details/binary-classification/reference/data-quality/data-point-distribution/index.jsx, ui/src/container/models/Details/multi-classification/current/data-quality/data-point-distribution/index.jsx, ui/src/container/models/Details/multi-classification/reference/data-quality/data-point-distribution/index.jsx, ui/src/container/models/Details/regression/current/data-quality/data-point-distribution/index.jsx, ui/src/container/models/Details/regression/reference/data-quality/data-point-distribution/index.jsx, ui/src/styles/index.less, ui/yarn.lock
- improve charts header legend
- add new rbit-design-system version
=> fix(ui): improve charts header legend

spark/jobs/metrics/hellinger_distance.py, spark/tests/hellinger_distance_test.py
This PR implements the Hellinger Distance job spark.
It is a method to detect a drift for both discrete and continuous variables.
=> feat: hellinger distance for drift detection

spark/jobs/metrics/jensen_shannon_distance.py, spark/tests/jensen_shannon_distance_test.py
This PR implements Jensen Shannon Distance as a Drift Detector.
=> feat: adding Jensen-Shannon Distance and test

ui/package.json, ui/src/components/modals/add-new-model/index.jsx, ui/src/components/modals/add-new-model/step-one/body.jsx, ui/src/components/modals/add-new-model/step-three/body.jsx, ui/src/components/modals/add-new-model/text-generation/index.jsx, ui/src/components/modals/current-import-detail-modal/body.jsx, ui/src/components/modals/current-import-detail-modal/index.jsx, ui/src/container/app/bottom-menu/index.jsx, ui/src/container/models/Details/binary-classification/current/data-drift/header/index.jsx, ui/src/container/models/Details/binary-classification/current/data-quality/data-point-distribution/index.jsx, ui/src/container/models/Details/binary-classification/current/index.jsx, ui/src/container/models/Details/binary-classification/reference/data-quality/data-point-distribution/index.jsx, ui/src/container/models/Details/binary-classification/reference/index.jsx, ui/src/container/models/Details/multi-classification/current/data-drift/header/index.jsx, ui/src/container/models/Details/multi-classification/current/data-quality/data-point-distribution/index.jsx, ui/src/container/models/Details/multi-classification/current/index.jsx, ui/src/container/models/Details/multi-classification/reference/data-quality/data-point-distribution/index.jsx, ui/src/container/models/Details/multi-classification/reference/index.jsx, ui/src/container/models/Details/regression/current/data-drift/header/index.jsx, ui/src/container/models/Details/regression/current/data-quality/data-point-distribution/index.jsx, ui/src/container/models/Details/regression/current/index.jsx, ui/src/container/models/Details/regression/current/model-quality/index.jsx, ui/src/container/models/Details/regression/reference/data-quality/data-point-distribution/index.jsx, ui/src/container/models/Details/regression/reference/index.jsx, ui/src/container/models/Details/regression/reference/model-quality/index.jsx, ui/src/container/models/Details/secondary-column/content.jsx, ui/vite.config.js, ui/yarn.lock
update design-system version and fix
=> feat(ui): update design-system version and fix

api/app/models/metrics/embeddings_dto.py, api/app/routes/metrics_route.py, api/app/services/metrics_service.py, api/tests/routes/metrics_route_test.py, api/tests/services/metrics_service_test.py
add current embeddings metrics endpoint
refactoring metrics service
edit tests
=> feat: add current embeddings metrics endpoint

spark/jobs/completion_job.py, spark/jobs/current_job.py, spark/jobs/reference_job.py
Add minimal minio handling over https and http.
If the url environment variable is set we assume it is minio, and if it is https we skip the verification
=> feat: add minimal minio handling

spark/jobs/completion_job.py, spark/jobs/current_job.py, spark/jobs/embeddings_current_job.py, spark/jobs/embeddings_reference_job.py, spark/jobs/reference_job.py
Disable check certificates if minio over https
=> fix: disable check certificates
